spring:
  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: <username>
    password: <password>
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

translation:
  api:
    url: https://translate.api.cloud.yandex.net/translate/v2/translate
    key: <your-api-key>
